Revamped package versioning, added NuGet.org publishing, did general cleanup.
* Added .editorconfig
* Added publishing to NuGet.org
* Completely tore out "smart" versioning system (it was more trouble than it was wroth.)
* Enabled using the informational version for the package version now that GitHub Packages doesn't choke on build metadata.
* Removed x64 restrictions from ClangSharp.Pathogen (the assemblies aren't really x64-specific, the runtime is.)
* Removed VersionPrefix from both projects. (We don't really support them shipping separately.)
* Added Directory.Build.* protection to the LLVM Visual Studio CMake output folder
* Modified Directory.Build.* pattern to match Biohazrd.
* Enabled embedding untracked sources (this is required for NuGet Package Explorer determinism checks to be happy.)
* Added building to central bin/obj folders.
* Enabled error if there's no NuGet packages to upload.
* Changed the BuildOutput artifact to be less aggressive and to upload even when building failed.
* Added disclaimer to NuGet package description that ClangSharp.Pathogen is primarily intended to support Biohazrd.

Fixes https://github.com/InfectedLibraries/ClangSharp.Pathogen/issues/3
Contributes to https://github.com/InfectedLibraries/Biohazrd/issues/214

diff --git a/.github/workflows/ClangSharp.Pathogen.yml b/.github/workflows/ClangSharp.Pathogen.yml
--- a/.github/workflows/ClangSharp.Pathogen.yml
+++ b/.github/workflows/ClangSharp.Pathogen.yml
@@ -1,23 +1,24 @@
 name: ClangSharp.Pathogen
 on:
   push:
+    # This prevents tag pushes from triggering this workflow
     branches: ['*']
   pull_request:
+  release:
+    types: [published]
   workflow_dispatch:
     inputs:
+      version:
+        description: "Version"
+        default: ""
       will_publish_packages:
         description: "Publish packages?"
-        default: "false"
-      preview_release_version:
-        description: "Preview release version"
-        default: ""
-      do_full_release:
-        description: "Full release?"
         default: "false"
 env:
   DOTNET_NOLOGO: true
   DOTNET_CLI_TELEMETRY_OPTOUT: true
   DOTNET_GENERATE_ASPNET_CERTIFICATE: false
+  ContinuousIntegrationBuild: true
 jobs:
   build-llvm:
     strategy:
@@ -168,20 +169,15 @@ jobs:
         run: python .github/workflows/configure-build.py
         env:
           github_event_name: ${{github.event_name}}
-          github_repository_owner: ${{github.repository_owner}}
           github_run_number: ${{github.run_number}}
-          github_ref: ${{github.ref}}
-          is_official_source: ${{secrets.is_official_source}}
-          input_will_publish_packages: ${{github.event.inputs.will_publish_packages}}
-          input_preview_release_version: ${{github.event.inputs.preview_release_version}}
-          input_do_full_release: ${{github.event.inputs.do_full_release}}
+          release_version: ${{github.event.release.tag_name}}
+          workflow_dispatch_version: ${{github.event.inputs.version}}
 
       # ----------------------------------------------------------------------- Build ClangSharp.Pathogen
       - name: Restore
         run: dotnet restore
 
       - name: Build
-        id: build
         run: dotnet build --no-restore
 
       - name: Pack
@@ -191,13 +187,16 @@ jobs:
       # ----------------------------------------------------------------------- Collect Artifacts
       - name: Collect Build Outputs
         uses: actions/upload-artifact@v2
-        # We always want to collect build outputs when they were produced
-        if: steps.build.outcome == 'success' && always()
+        # We always want to collect any build outputs that were created even if building failed
+        if: always()
         with:
           name: BuildOutputs
+          # The build* folders is fine here because LLVM was built in another job so these will just be the stuff required to build
           path: |
-            **/bin/**
-            **/obj/**
+            bin/**
+            obj/**
+            build*/**
+            !build-*.*
 
       - name: Collect NuGet Packages
         uses: actions/upload-artifact@v2
@@ -205,13 +204,80 @@ jobs:
         if: steps.pack.outcome == 'success' && always()
         with:
           name: Packages
+          if-no-files-found: error
           path: packages/**
 
-  publish-packages:
-    name: Publish ClangSharp.Pathogen
+  publish-packages-github:
+    name: Publish to GitHub
     runs-on: ubuntu-latest
     needs: build-dotnet
-    if: needs.build-dotnet.outputs.publish-to-github == 'true'
+    # Pushes to main always publish CI packages
+    # Published releases always publish packages
+    # A manual workflow only publishes packages if explicitly enabled
+    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && github.event.inputs.will_publish_packages == 'true')
+    steps:
+      # ----------------------------------------------------------------------- Setup .NET
+      - name: Setup .NET
+        uses: actions/setup-dotnet@v1
+        with:
+          dotnet-version: 5.0.x
+
+      # ----------------------------------------------------------------------- Download built packages
+      - name: Download built packages
+        uses: actions/download-artifact@v2
+        with:
+          name: Packages
+      
+      # ----------------------------------------------------------------------- Upload release assets
+      - name: Upload release assets
+        if: github.event_name == 'release'
+        uses: actions/github-script@v4
+        with:
+          user-agent: actions/github-script for ${{github.repository}}
+          script: |
+            const fs = require('fs').promises;
+            const path = require('path');
+            const upload_url = context.payload.release.upload_url;
+
+            if (!upload_url) {
+                throw "Missing release asset upload URL!";
+            }
+
+            for (let filePath of await fs.readdir('.')) {
+                const fileExtension = path.extname(filePath);
+                if (fileExtension != '.nupkg' && fileExtension != '.snupkg') {
+                    continue;
+                }
+
+                console.log(`Uploading '${filePath}'`);
+                const contentLength = (await fs.stat(filePath)).size;
+                const fileContents = await fs.readFile(filePath);
+                await github.repos.uploadReleaseAsset({
+                    url: upload_url,
+                    headers: {
+                        'content-type': 'application/octet-stream',
+                        'content-length': contentLength
+                    },
+                    name: path.basename(filePath),
+                    data: fileContents
+                });
+            }
+
+      # ----------------------------------------------------------------------- Push to GitHub Packages
+      - name: Push to GitHub Packages
+        run: dotnet nuget push "*.nupkg" --skip-duplicate --no-symbols true --api-key ${{secrets.GITHUB_TOKEN}} --source https://nuget.pkg.github.com/${{github.repository_owner}}
+        env:
+          # This is a workaround for https://github.com/NuGet/Home/issues/9775
+          DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER: 0
+  
+  publish-packages-nuget-org:
+    name: Publish to NuGet.org
+    runs-on: ubuntu-latest
+    needs: build-dotnet
+    environment: NuGet.org
+    # Release builds always publish packages to NuGet.org
+    # Workflow dispatch builds will only publish packages if enabled and an explicit version number is given
+    if: github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && github.event.inputs.will_publish_packages == 'true' && github.event.inputs.version != '')
     steps:
       # ----------------------------------------------------------------------- Setup .NET
       - name: Setup .NET
@@ -225,16 +291,16 @@ jobs:
         with:
           name: Packages
 
-      # ----------------------------------------------------------------------- Publish ClangSharp.Pathogen
-      - name: Push packages
-        run: dotnet nuget push "*.nupkg" --no-symbols true --api-key ${{secrets.GITHUB_TOKEN}} --source https://nuget.pkg.github.com/${{github.repository_owner}}
+      # ----------------------------------------------------------------------- Push to NuGet.org
+      - name: Push to NuGet.org
+        run: dotnet nuget push "*.nupkg" --api-key ${{secrets.NUGET_API_KEY}} --source ${{secrets.NUGET_API_URL}}
         env:
           # This is a workaround for https://github.com/NuGet/Home/issues/9775
           DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER: 0
 
   send-ci-failure-notification:
     name: Send CI Failure Notification
-    needs: [build-llvm, build-dotnet, publish-packages]
+    needs: [build-llvm, build-dotnet, publish-packages-github, publish-packages-nuget-org]
     if: failure() && github.event_name != 'pull_request'
     continue-on-error: true
     runs-on: ubuntu-latest
